name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["proffalken/3"]
assignees:
  - proffalken
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the library are you running?
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: What hardware are you seeing the problem on?
      multiple: true
      options:
        - ESP32
        - ESP8266
        - RP2040
        - Something else
  - type: input
    id: other_hardware
    attributes:
      label: Other hardware
      description: If you're using something other than the ones in the list above, please put it here
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/proffalken/otel-embedded-cpp/blob/main/CODE_OF_CONDUCT). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

