name: Feature Request
description: Need something new added to the library? This is the form for you!
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["proffalken/3"]
assignees:
  - proffalken
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what_do_you_want_to_see
    attributes:
      label: What do you want to see?
      description: What are we missing in our project?
      placeholder: Tell us what you see!
      value: "A new feature"
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: What hardware are you using?
      multiple: true
      options:
        - ESP32
        - ESP8266
        - RP2040
        - Something else
  - type: input
    id: other_hardware
    attributes:
      label: Other hardware
      description: If you're using something other than the ones in the list above, please put it here
    validations:
      required: false
  - type: textarea
    id: other_info
    attributes:
      label: What else can you tell us to help us implement this?
      description: Is there another project that does similar things? Do you have example code? Please post it here!
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/proffalken/otel-embedded-cpp/blob/main/CODE_OF_CONDUCT). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

