name: Validate PlatformIO Library

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install -U platformio

      - name: PlatformIO Update
        run: |
          pio update

      - name: Build for ESP32 (esp32dev)
        run: |
          platformio ci examples/basic/main.cpp --project-conf platformio.ini --lib "." -e esp32dev

      - name: Build for Pico W (rpipicow)
        run: |
          platformio ci examples/basic/main.cpp --project-conf platformio.ini --lib "." -e rpipicow

      - name: Build for ESP8266 (esp8266 d1_mini)
        run: |
          platformio ci examples/basic/main.cpp --project-conf platformio.ini --lib "." -e esp8266


